spring:
  application:
    name: pawEver
  profiles:
    default: local
  task:
    scheduling:
      pool:
        size: 5
logging:
  config: classpath:logback-spring.xml
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
openapi:
  service-key: ${OPENAPI_SERVICE_KEY}
kakao:
  api:
    key: ${KAKAO_REST_API_KEY}
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_ACCESS_KEY}
    s3:
      bucket-name: paweverbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false


